// ============================================================
// lib/postgres.ts  —  Kysely + pg singleton
// ============================================================

import { Kysely, PostgresDialect } from "kysely";
import pg from "pg";

// Auto-generated by `kysely-codegen` from the actual schema.
// Check in to source control and regenerate after migrations.
interface Database {
  repos: {
    id:             string;
    url:            string;
    name:           string;
    branch:         string | null;
    status:         "queued" | "cloning" | "analyzing" | "indexing" | "complete" | "failed";
    current_job_id: string | null;
    created_at:     Date;
    updated_at:     Date;
  };
  files: {
    repo_id:        string;
    file_path:      string;
    language:       string;
    loc:            number;
    complexity:     number;
    function_count: number;
    class_count:    number;
    import_count:   number;
    export_count:   number;
    parse_errors:   number;
    updated_at:     Date;
  };
  file_symbols: {
    file_path:   string;
    symbol_name: string;
    kind:        "function" | "class" | "variable" | "type";
  };
}

let _db: Kysely<Database> | null = null;

export function getDb(): Kysely<Database> {
  if (_db) return _db;

  const pool = new pg.Pool({
    connectionString: process.env.DATABASE_URL ?? "postgres://postgres:postgres@localhost:5432/codevis",
    max: 20,
    idleTimeoutMillis: 30_000,
    connectionTimeoutMillis: 5_000,
  });

  _db = new Kysely<Database>({
    dialect: new PostgresDialect({ pool }),
  });

  return _db;
}

export async function closeDb(): Promise<void> {
  if (_db) { await _db.destroy(); _db = null; }
}


// ============================================================
// lib/neo4j.ts  —  Neo4j Driver singleton
// ============================================================

import neo4j, { type Driver } from "neo4j-driver";

let _driver: Driver | null = null;

export function getNeo4jDriver(): Driver {
  if (_driver) return _driver;

  _driver = neo4j.driver(
    process.env.NEO4J_URI      ?? "bolt://localhost:7687",
    neo4j.auth.basic(
      process.env.NEO4J_USER     ?? "neo4j",
      process.env.NEO4J_PASSWORD ?? "password"
    ),
    {
      maxConnectionPoolSize: 50,
      connectionAcquisitionTimeout: 5_000,
    }
  );

  return _driver;
}


// ============================================================
// lib/redis.ts  —  ioredis singleton (shared with BullMQ)
// ============================================================

import { Redis } from "ioredis";

let _redis: Redis | null = null;

export function getRedisConnection(): Redis {
  if (_redis) return _redis;

  _redis = new Redis(process.env.REDIS_URL ?? "redis://localhost:6379", {
    maxRetriesPerRequest: null,
    enableReadyCheck: false,
    lazyConnect: false,
  });

  _redis.on("error", (err) => {
    console.error("[Redis]", err.message);
  });

  return _redis;
}


// ============================================================
// lib/queue.ts  —  BullMQ Queue singleton (same as worker/src)
// ============================================================

import { Queue } from "bullmq";
import { QUEUE } from "@codevis/worker/job.types";

let _queue: Queue | null = null;

export function getRepoAnalysisQueue(): Queue {
  if (_queue) return _queue;
  _queue = new Queue(QUEUE.REPO_ANALYSIS, {
    connection: getRedisConnection(),
  });
  return _queue;
}
